### ISSUE TITLE
T1.2: Crear el formulario de iniciar sesión.

### ISSUE THREAD

**Issue by lissavcasas** [elment9/lim-2018-05-bc-core-pm-socialnetwork#10]
- [x] Crear interfaz básica con HTML y CSS.
- [x] Responsive

**Comment by EstefaniaTelis** [comment]
Listo el responsive. Sólo falta hacer pull request 😍 
![login-responsive](https://user-images.githubusercontent.com/38727384/43017339-57411340-8c1b-11e8-8021-f95bf72b83c6.jpg)

**Comment by elment9** [comment]
Genial 💃
