### ISSUE TITLE
Definir herramientas para organización del trabajo. 

### ISSUE THREAD

**Issue by lissavcasas** [elment9/lim-2018-05-bc-core-pm-socialnetwork#11]
- [x] Crear tablero Kanban para sprint 1. 
- [x] Crear issues & milestones en Github 
- [x] Crear tablero en Trello.

**Comment by lissavcasas** [comment]
Done! 

**Tablero Kan Ban** : [https://trello.com/b/ns4dBV1T/red-social](https://trello.com/b/ns4dBV1T/red-social)

**Comment by EstefaniaTelis** [comment]
Ready!
