### ISSUE TITLE
T0.2: Síntesis y definición 

### ISSUE THREAD

**Issue by lissavcasas** [elment9/lim-2018-05-bc-core-pm-socialnetwork#17]
0.2.2. Descubrir insights de la data recolectada en la fase de investigación

- [x] Definir problemática y objetivo.
- [x] Definir público objetivo.

0.2.3. Definir nombre del producto

- [x]  Lluvia de ideas con posibles nombres
- [x]  Testear propuestas

0.2.4. Definir slogan del producto

- [x]   Lluvia de ideas con posibles slogans
- [x]  Testear propuestas

**Comment by EstefaniaTelis** [comment]
Ready (y)
