### ISSUE TITLE
T0.4: Prototipado

### ISSUE THREAD

**Issue by lissavcasas** [elment9/lim-2018-05-bc-core-pm-socialnetwork#19]
- [x] Corregir sketch de baja fidelidad

- [x] Testear sketch con usuarios

- [x] Hacer sketch de media fidelidad

- [x] Testear con usuarios

- [x] Hacer sketch de alta fidelidad

**Comment by EstefaniaTelis** [comment]
Sketchs en readme + prototipo de mediana fidelidad en Figma con link. Ready!
